### ISSUE TITLE
这是我开发的Chrome插件

### ISSUE THREAD

**Issue by Pearyman** [iuunhao/ChromePlugIns#1]
插件名称：fed_navigation

插件性质：前端开发必备网站

插件地址：谷歌商店地址（https://chrome.google.com/webstore/detail/%E5%89%8D%E7%AB%AF%E5%AF%BC%E8%88%AA/kimhkkondjpjhnllknndckjppgbjnjai?hl=zh-CN）

插件描述：前端、设计必备网站

**Comment by iuunhao** [comment]
插件不错，很喜欢。👻
